---
prometheus_vars:
  kubernetes:
    alertmanager:
      gateway:
        service: monitoring-kube-prometheus-alertmanager
        subdomain: alertmanager
      infrastructure:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.40.23
      replicas: 2
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 64Mi
      storage: 5Gi
    helm:
      chart:
        name: kube-prometheus-stack
        prefix: monitoring
        version: v60.4.0
      repository:
        name: helm-charts
        org: prometheus-community
        url: https://prometheus-community.github.io
    grafana:
      gateway:
        service: monitoring-grafana
        subdomain: grafana
      infrastructure:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.40.24
      secret:
        name: grafana-secret
      user:
        name: admin
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37343533353735613339316536373631356530303234316438653236623637383139343432643432
          3062333037353161316162383739373566303932383836660a393564356564613330646438383231
          39326366303065356165653330383134343636346532353961653232323536336562646437613534
          3633626362653464340a313335303633383038616232646535323838376664646233623961326562
          35383333383830643061396265396663346665383633633266353337633463393038
    namespace: kube-system
    prometheus:
      gateway:
        service: monitoring-kube-prometheus-prometheus
        subdomain: prometheus
      infrastructure:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.40.25
      resources:
        limits:
          cpu: 1
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 64Mi
      storage: 50Gi
